mysql:
    port: '3306'
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: gin-temp
    username: root
    password: 'root123'
    path: 'localhost'
    engine: ''
    log_mode: error
    max_idle_conns: 10
    max_open_conns: 100
    singular: false
    log_zap: true
jwt:
    secret: kFtIlHcc4hscxA9IUx1U9ZC1LY3BAA
    time_out: 604800
system:
    router_prefix: 'api/v1'
    port: 8000
zap:
    level: info
    prefix: ''
    format: console
    director: log
    encode_level: LowercaseColorLevelEncoder
    stacktrace_key: stacktrace
    max-age: 0
    show_line: true
    log_in_console: true
